<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Assessment;
use App\Models\AssessmentQuestion;
use Illuminate\Support\Str;

class AssessmentSeeder extends Seeder
{
    public function run(): void
    {
        $assessments = [
            [
                'title' => 'Depression Assessment',
                'slug' => 'depression-assessment',
                'description' => 'A comprehensive assessment to help identify symptoms of depression and their severity. This tool can help you understand your mental health better.',
                'category' => 'Mental Health',
                'icon' => 'depression',
                'color' => '#EF4444',
                'duration_minutes' => 15,
                'question_count' => 10,
                'sort_order' => 1,
                'meta_title' => 'Depression Assessment - Mental Health Screening',
                'meta_description' => 'Take our comprehensive depression assessment to identify symptoms and get personalized recommendations.',
            ],
            [
                'title' => 'Anxiety Assessment',
                'slug' => 'anxiety-assessment',
                'description' => 'Evaluate your anxiety levels and learn about different types of anxiety disorders. Get insights into your stress patterns.',
                'category' => 'Mental Health',
                'icon' => 'anxiety',
                'color' => '#F59E0B',
                'duration_minutes' => 12,
                'question_count' => 10,
                'sort_order' => 2,
                'meta_title' => 'Anxiety Assessment - Stress & Anxiety Screening',
                'meta_description' => 'Complete our anxiety assessment to understand your stress levels and get coping strategies.',
            ],
            [
                'title' => 'Stress Assessment',
                'slug' => 'stress-assessment',
                'description' => 'Measure your current stress levels and identify sources of stress in your life. Learn effective stress management techniques.',
                'category' => 'Wellness',
                'icon' => 'stress',
                'color' => '#8B5CF6',
                'duration_minutes' => 10,
                'question_count' => 10,
                'sort_order' => 3,
                'meta_title' => 'Stress Assessment - Stress Level Evaluation',
                'meta_description' => 'Assess your stress levels and discover personalized stress management strategies.',
            ],
            [
                'title' => 'Sleep Quality Assessment',
                'slug' => 'sleep-quality-assessment',
                'description' => 'Evaluate your sleep patterns and quality. Get personalized recommendations for better sleep hygiene.',
                'category' => 'Wellness',
                'icon' => 'sleep',
                'color' => '#3B82F6',
                'duration_minutes' => 8,
                'question_count' => 10,
                'sort_order' => 4,
                'meta_title' => 'Sleep Quality Assessment - Sleep Health Evaluation',
                'meta_description' => 'Assess your sleep quality and get recommendations for better rest and recovery.',
            ],
            [
                'title' => 'Relationship Assessment',
                'slug' => 'relationship-assessment',
                'description' => 'Evaluate your relationship patterns and communication skills. Improve your interpersonal connections.',
                'category' => 'Relationships',
                'icon' => 'relationships',
                'color' => '#10B981',
                'duration_minutes' => 12,
                'question_count' => 10,
                'sort_order' => 5,
                'meta_title' => 'Relationship Assessment - Interpersonal Skills Evaluation',
                'meta_description' => 'Assess your relationship patterns and communication skills for healthier connections.',
            ],
            [
                'title' => 'General Wellness Assessment',
                'slug' => 'general-wellness-assessment',
                'description' => 'A comprehensive assessment of your overall mental health and wellness. Get a complete picture of your well-being.',
                'category' => 'Wellness',
                'icon' => 'wellness',
                'color' => '#06B6D4',
                'duration_minutes' => 20,
                'question_count' => 10,
                'sort_order' => 6,
                'meta_title' => 'General Wellness Assessment - Complete Mental Health Evaluation',
                'meta_description' => 'Comprehensive mental health and wellness assessment for complete well-being insights.',
            ],
        ];

        foreach ($assessments as $assessmentData) {
            $assessment = Assessment::create($assessmentData);

            // Create sample questions for each assessment
            $this->createSampleQuestions($assessment);
        }
    }

    private function createSampleQuestions($assessment)
    {
        $questions = [
            'Depression Assessment' => [
                [
                    'question_text' => 'How often have you felt down, depressed, or hopeless in the past two weeks?',
                    'question_type' => 'multiple_choice',
                    'options' => [
                        ['text' => 'Not at all', 'value' => 0],
                        ['text' => 'Several days', 'value' => 1],
                        ['text' => 'More than half the days', 'value' => 2],
                        ['text' => 'Nearly every day', 'value' => 3],
                    ],
                    'sort_order' => 1,
                    'weight' => 3,
                ],
                [
                    'question_text' => 'How often have you had little interest or pleasure in doing things?',
                    'question_type' => 'multiple_choice',
                    'options' => [
                        ['text' => 'Not at all', 'value' => 0],
                        ['text' => 'Several days', 'value' => 1],
                        ['text' => 'More than half the days', 'value' => 2],
                        ['text' => 'Nearly every day', 'value' => 3],
                    ],
                    'sort_order' => 2,
                    'weight' => 3,
                ],
                [
                    'question_text' => 'How often have you had trouble falling asleep, staying asleep, or sleeping too much?',
                    'question_type' => 'multiple_choice',
                    'options' => [
                        ['text' => 'Not at all', 'value' => 0],
                        ['text' => 'Several days', 'value' => 1],
                        ['text' => 'More than half the days', 'value' => 2],
                        ['text' => 'Nearly every day', 'value' => 3],
                    ],
                    'sort_order' => 3,
                    'weight' => 2,
                ],
                [
                    'question_text' => 'How often have you felt tired or had little energy?',
                    'question_type' => 'multiple_choice',
                    'options' => [
                        ['text' => 'Not at all', 'value' => 0],
                        ['text' => 'Several days', 'value' => 1],
                        ['text' => 'More than half the days', 'value' => 2],
                        ['text' => 'Nearly every day', 'value' => 3],
                    ],
                    'sort_order' => 4,
                    'weight' => 2,
                ],
                [
                    'question_text' => 'How often have you had poor appetite or overeating?',
                    'question_type' => 'multiple_choice',
                    'options' => [
                        ['text' => 'Not at all', 'value' => 0],
                        ['text' => 'Several days', 'value' => 1],
                        ['text' => 'More than half the days', 'value' => 2],
                        ['text' => 'Nearly every day', 'value' => 3],
                    ],
                    'sort_order' => 5,
                    'weight' => 2,
                ],
                [
                    'question_text' => 'How often have you felt bad about yourself or that you are a failure?',
                    'question_type' => 'multiple_choice',
                    'options' => [
                        ['text' => 'Not at all', 'value' => 0],
                        ['text' => 'Several days', 'value' => 1],
                        ['text' => 'More than half the days', 'value' => 2],
                        ['text' => 'Nearly every day', 'value' => 3],
                    ],
                    'sort_order' => 6,
                    'weight' => 3,
                ],
                [
                    'question_text' => 'How often have you had trouble concentrating on things?',
                    'question_type' => 'multiple_choice',
                    'options' => [
                        ['text' => 'Not at all', 'value' => 0],
                        ['text' => 'Several days', 'value' => 1],
                        ['text' => 'More than half the days', 'value' => 2],
                        ['text' => 'Nearly every day', 'value' => 3],
                    ],
                    'sort_order' => 7,
                    'weight' => 2,
                ],
                [
                    'question_text' => 'How often have you been moving or speaking so slowly that other people could have noticed?',
                    'question_type' => 'multiple_choice',
                    'options' => [
                        ['text' => 'Not at all', 'value' => 0],
                        ['text' => 'Several days', 'value' => 1],
                        ['text' => 'More than half the days', 'value' => 2],
                        ['text' => 'Nearly every day', 'value' => 3],
                    ],
                    'sort_order' => 8,
                    'weight' => 2,
                ],
                [
                    'question_text' => 'How often have you had thoughts that you would be better off dead?',
                    'question_type' => 'multiple_choice',
                    'options' => [
                        ['text' => 'Not at all', 'value' => 0],
                        ['text' => 'Several days', 'value' => 1],
                        ['text' => 'More than half the days', 'value' => 2],
                        ['text' => 'Nearly every day', 'value' => 3],
                    ],
                    'sort_order' => 9,
                    'weight' => 4,
                ],
                [
                    'question_text' => 'How often have you had thoughts of hurting yourself?',
                    'question_type' => 'multiple_choice',
                    'options' => [
                        ['text' => 'Not at all', 'value' => 0],
                        ['text' => 'Several days', 'value' => 1],
                        ['text' => 'More than half the days', 'value' => 2],
                        ['text' => 'Nearly every day', 'value' => 3],
                    ],
                    'sort_order' => 10,
                    'weight' => 4,
                ],
            ],
            'Anxiety Assessment' => [
                [
                    'question_text' => 'How often do you feel nervous, anxious, or on edge?',
                    'question_type' => 'multiple_choice',
                    'options' => [
                        ['text' => 'Not at all', 'value' => 0],
                        ['text' => 'Several days', 'value' => 1],
                        ['text' => 'More than half the days', 'value' => 2],
                        ['text' => 'Nearly every day', 'value' => 3],
                    ],
                    'sort_order' => 1,
                    'weight' => 3,
                ],
                [
                    'question_text' => 'How often do you worry too much about different things?',
                    'question_type' => 'multiple_choice',
                    'options' => [
                        ['text' => 'Not at all', 'value' => 0],
                        ['text' => 'Several days', 'value' => 1],
                        ['text' => 'More than half the days', 'value' => 2],
                        ['text' => 'Nearly every day', 'value' => 3],
                    ],
                    'sort_order' => 2,
                    'weight' => 3,
                ],
                [
                    'question_text' => 'How often do you have trouble relaxing?',
                    'question_type' => 'multiple_choice',
                    'options' => [
                        ['text' => 'Not at all', 'value' => 0],
                        ['text' => 'Several days', 'value' => 1],
                        ['text' => 'More than half the days', 'value' => 2],
                        ['text' => 'Nearly every day', 'value' => 3],
                    ],
                    'sort_order' => 3,
                    'weight' => 2,
                ],
                [
                    'question_text' => 'How often do you become easily annoyed or irritable?',
                    'question_type' => 'multiple_choice',
                    'options' => [
                        ['text' => 'Not at all', 'value' => 0],
                        ['text' => 'Several days', 'value' => 1],
                        ['text' => 'More than half the days', 'value' => 2],
                        ['text' => 'Nearly every day', 'value' => 3],
                    ],
                    'sort_order' => 4,
                    'weight' => 2,
                ],
                [
                    'question_text' => 'How often do you feel afraid as if something awful might happen?',
                    'question_type' => 'multiple_choice',
                    'options' => [
                        ['text' => 'Not at all', 'value' => 0],
                        ['text' => 'Several days', 'value' => 1],
                        ['text' => 'More than half the days', 'value' => 2],
                        ['text' => 'Nearly every day', 'value' => 3],
                    ],
                    'sort_order' => 5,
                    'weight' => 3,
                ],
                [
                    'question_text' => 'How often do you have trouble falling or staying asleep?',
                    'question_type' => 'multiple_choice',
                    'options' => [
                        ['text' => 'Not at all', 'value' => 0],
                        ['text' => 'Several days', 'value' => 1],
                        ['text' => 'More than half the days', 'value' => 2],
                        ['text' => 'Nearly every day', 'value' => 3],
                    ],
                    'sort_order' => 6,
                    'weight' => 2,
                ],
                [
                    'question_text' => 'How often do you have muscle tension or aches?',
                    'question_type' => 'multiple_choice',
                    'options' => [
                        ['text' => 'Not at all', 'value' => 0],
                        ['text' => 'Several days', 'value' => 1],
                        ['text' => 'More than half the days', 'value' => 2],
                        ['text' => 'Nearly every day', 'value' => 3],
                    ],
                    'sort_order' => 7,
                    'weight' => 2,
                ],
                [
                    'question_text' => 'How often do you feel restless or keyed up?',
                    'question_type' => 'multiple_choice',
                    'options' => [
                        ['text' => 'Not at all', 'value' => 0],
                        ['text' => 'Several days', 'value' => 1],
                        ['text' => 'More than half the days', 'value' => 2],
                        ['text' => 'Nearly every day', 'value' => 3],
                    ],
                    'sort_order' => 8,
                    'weight' => 2,
                ],
                [
                    'question_text' => 'How often do you have difficulty concentrating?',
                    'question_type' => 'multiple_choice',
                    'options' => [
                        ['text' => 'Not at all', 'value' => 0],
                        ['text' => 'Several days', 'value' => 1],
                        ['text' => 'More than half the days', 'value' => 2],
                        ['text' => 'Nearly every day', 'value' => 3],
                    ],
                    'sort_order' => 9,
                    'weight' => 2,
                ],
                [
                    'question_text' => 'How often do you feel tired or have little energy?',
                    'question_type' => 'multiple_choice',
                    'options' => [
                        ['text' => 'Not at all', 'value' => 0],
                        ['text' => 'Several days', 'value' => 1],
                        ['text' => 'More than half the days', 'value' => 2],
                        ['text' => 'Nearly every day', 'value' => 3],
                    ],
                    'sort_order' => 10,
                    'weight' => 2,
                ],
            ],
            'Stress Assessment' => [
                [
                    'question_text' => 'How would you rate your current stress level?',
                    'question_type' => 'scale',
                    'options' => [
                        ['text' => 'Very Low', 'value' => 1],
                        ['text' => 'Low', 'value' => 2],
                        ['text' => 'Moderate', 'value' => 3],
                        ['text' => 'High', 'value' => 4],
                        ['text' => 'Very High', 'value' => 5],
                    ],
                    'sort_order' => 1,
                    'weight' => 2,
                ],
                [
                    'question_text' => 'How often do you feel overwhelmed by your responsibilities?',
                    'question_type' => 'multiple_choice',
                    'options' => [
                        ['text' => 'Never', 'value' => 0],
                        ['text' => 'Rarely', 'value' => 1],
                        ['text' => 'Sometimes', 'value' => 2],
                        ['text' => 'Often', 'value' => 3],
                        ['text' => 'Always', 'value' => 4],
                    ],
                    'sort_order' => 2,
                    'weight' => 2,
                ],
                [
                    'question_text' => 'How well do you handle unexpected changes or problems?',
                    'question_type' => 'scale',
                    'options' => [
                        ['text' => 'Very Poorly', 'value' => 1],
                        ['text' => 'Poorly', 'value' => 2],
                        ['text' => 'Moderately', 'value' => 3],
                        ['text' => 'Well', 'value' => 4],
                        ['text' => 'Very Well', 'value' => 5],
                    ],
                    'sort_order' => 3,
                    'weight' => 2,
                ],
                [
                    'question_text' => 'How often do you feel irritable or angry?',
                    'question_type' => 'multiple_choice',
                    'options' => [
                        ['text' => 'Never', 'value' => 0],
                        ['text' => 'Rarely', 'value' => 1],
                        ['text' => 'Sometimes', 'value' => 2],
                        ['text' => 'Often', 'value' => 3],
                        ['text' => 'Always', 'value' => 4],
                    ],
                    'sort_order' => 4,
                    'weight' => 2,
                ],
                [
                    'question_text' => 'How often do you have trouble sleeping due to stress?',
                    'question_type' => 'multiple_choice',
                    'options' => [
                        ['text' => 'Never', 'value' => 0],
                        ['text' => 'Rarely', 'value' => 1],
                        ['text' => 'Sometimes', 'value' => 2],
                        ['text' => 'Often', 'value' => 3],
                        ['text' => 'Always', 'value' => 4],
                    ],
                    'sort_order' => 5,
                    'weight' => 2,
                ],
                [
                    'question_text' => 'How often do you feel anxious or worried?',
                    'question_type' => 'multiple_choice',
                    'options' => [
                        ['text' => 'Never', 'value' => 0],
                        ['text' => 'Rarely', 'value' => 1],
                        ['text' => 'Sometimes', 'value' => 2],
                        ['text' => 'Often', 'value' => 3],
                        ['text' => 'Always', 'value' => 4],
                    ],
                    'sort_order' => 6,
                    'weight' => 2,
                ],
                [
                    'question_text' => 'How often do you feel physically tense or have muscle aches?',
                    'question_type' => 'multiple_choice',
                    'options' => [
                        ['text' => 'Never', 'value' => 0],
                        ['text' => 'Rarely', 'value' => 1],
                        ['text' => 'Sometimes', 'value' => 2],
                        ['text' => 'Often', 'value' => 3],
                        ['text' => 'Always', 'value' => 4],
                    ],
                    'sort_order' => 7,
                    'weight' => 2,
                ],
                [
                    'question_text' => 'How often do you feel like you have too much to do?',
                    'question_type' => 'multiple_choice',
                    'options' => [
                        ['text' => 'Never', 'value' => 0],
                        ['text' => 'Rarely', 'value' => 1],
                        ['text' => 'Sometimes', 'value' => 2],
                        ['text' => 'Often', 'value' => 3],
                        ['text' => 'Always', 'value' => 4],
                    ],
                    'sort_order' => 8,
                    'weight' => 2,
                ],
                [
                    'question_text' => 'How often do you feel like you have little control over your life?',
                    'question_type' => 'multiple_choice',
                    'options' => [
                        ['text' => 'Never', 'value' => 0],
                        ['text' => 'Rarely', 'value' => 1],
                        ['text' => 'Sometimes', 'value' => 2],
                        ['text' => 'Often', 'value' => 3],
                        ['text' => 'Always', 'value' => 4],
                    ],
                    'sort_order' => 9,
                    'weight' => 2,
                ],
                [
                    'question_text' => 'How often do you feel like you need a break or vacation?',
                    'question_type' => 'multiple_choice',
                    'options' => [
                        ['text' => 'Never', 'value' => 0],
                        ['text' => 'Rarely', 'value' => 1],
                        ['text' => 'Sometimes', 'value' => 2],
                        ['text' => 'Often', 'value' => 3],
                        ['text' => 'Always', 'value' => 4],
                    ],
                    'sort_order' => 10,
                    'weight' => 2,
                ],
            ],
            'Sleep Quality Assessment' => [
                [
                    'question_text' => 'How would you rate your overall sleep quality?',
                    'question_type' => 'scale',
                    'options' => [
                        ['text' => 'Very Poor', 'value' => 1],
                        ['text' => 'Poor', 'value' => 2],
                        ['text' => 'Fair', 'value' => 3],
                        ['text' => 'Good', 'value' => 4],
                        ['text' => 'Very Good', 'value' => 5],
                    ],
                    'sort_order' => 1,
                    'weight' => 2,
                ],
                [
                    'question_text' => 'How long does it usually take you to fall asleep?',
                    'question_type' => 'multiple_choice',
                    'options' => [
                        ['text' => 'Less than 15 minutes', 'value' => 0],
                        ['text' => '15-30 minutes', 'value' => 1],
                        ['text' => '30-60 minutes', 'value' => 2],
                        ['text' => 'More than 60 minutes', 'value' => 3],
                    ],
                    'sort_order' => 2,
                    'weight' => 2,
                ],
                [
                    'question_text' => 'How often do you wake up during the night?',
                    'question_type' => 'multiple_choice',
                    'options' => [
                        ['text' => 'Never', 'value' => 0],
                        ['text' => 'Once', 'value' => 1],
                        ['text' => '2-3 times', 'value' => 2],
                        ['text' => 'More than 3 times', 'value' => 3],
                    ],
                    'sort_order' => 3,
                    'weight' => 2,
                ],
                [
                    'question_text' => 'How often do you have trouble falling back asleep after waking up?',
                    'question_type' => 'multiple_choice',
                    'options' => [
                        ['text' => 'Never', 'value' => 0],
                        ['text' => 'Rarely', 'value' => 1],
                        ['text' => 'Sometimes', 'value' => 2],
                        ['text' => 'Often', 'value' => 3],
                    ],
                    'sort_order' => 4,
                    'weight' => 2,
                ],
                [
                    'question_text' => 'How often do you wake up feeling refreshed?',
                    'question_type' => 'multiple_choice',
                    'options' => [
                        ['text' => 'Never', 'value' => 3],
                        ['text' => 'Rarely', 'value' => 2],
                        ['text' => 'Sometimes', 'value' => 1],
                        ['text' => 'Often', 'value' => 0],
                    ],
                    'sort_order' => 5,
                    'weight' => 2,
                ],
                [
                    'question_text' => 'How often do you feel sleepy during the day?',
                    'question_type' => 'multiple_choice',
                    'options' => [
                        ['text' => 'Never', 'value' => 0],
                        ['text' => 'Rarely', 'value' => 1],
                        ['text' => 'Sometimes', 'value' => 2],
                        ['text' => 'Often', 'value' => 3],
                    ],
                    'sort_order' => 6,
                    'weight' => 2,
                ],
                [
                    'question_text' => 'How often do you use electronic devices before bedtime?',
                    'question_type' => 'multiple_choice',
                    'options' => [
                        ['text' => 'Never', 'value' => 0],
                        ['text' => 'Rarely', 'value' => 1],
                        ['text' => 'Sometimes', 'value' => 2],
                        ['text' => 'Often', 'value' => 3],
                    ],
                    'sort_order' => 7,
                    'weight' => 1,
                ],
                [
                    'question_text' => 'How often do you have caffeine in the afternoon or evening?',
                    'question_type' => 'multiple_choice',
                    'options' => [
                        ['text' => 'Never', 'value' => 0],
                        ['text' => 'Rarely', 'value' => 1],
                        ['text' => 'Sometimes', 'value' => 2],
                        ['text' => 'Often', 'value' => 3],
                    ],
                    'sort_order' => 8,
                    'weight' => 1,
                ],
                [
                    'question_text' => 'How often do you exercise regularly?',
                    'question_type' => 'multiple_choice',
                    'options' => [
                        ['text' => 'Never', 'value' => 3],
                        ['text' => 'Rarely', 'value' => 2],
                        ['text' => 'Sometimes', 'value' => 1],
                        ['text' => 'Often', 'value' => 0],
                    ],
                    'sort_order' => 9,
                    'weight' => 1,
                ],
                [
                    'question_text' => 'How often do you maintain a consistent sleep schedule?',
                    'question_type' => 'multiple_choice',
                    'options' => [
                        ['text' => 'Never', 'value' => 3],
                        ['text' => 'Rarely', 'value' => 2],
                        ['text' => 'Sometimes', 'value' => 1],
                        ['text' => 'Often', 'value' => 0],
                    ],
                    'sort_order' => 10,
                    'weight' => 2,
                ],
            ],
            'Relationship Assessment' => [
                [
                    'question_text' => 'How satisfied are you with your current relationships?',
                    'question_type' => 'scale',
                    'options' => [
                        ['text' => 'Very Dissatisfied', 'value' => 1],
                        ['text' => 'Dissatisfied', 'value' => 2],
                        ['text' => 'Neutral', 'value' => 3],
                        ['text' => 'Satisfied', 'value' => 4],
                        ['text' => 'Very Satisfied', 'value' => 5],
                    ],
                    'sort_order' => 1,
                    'weight' => 2,
                ],
                [
                    'question_text' => 'How often do you feel understood by your partner/friends?',
                    'question_type' => 'multiple_choice',
                    'options' => [
                        ['text' => 'Never', 'value' => 0],
                        ['text' => 'Rarely', 'value' => 1],
                        ['text' => 'Sometimes', 'value' => 2],
                        ['text' => 'Often', 'value' => 3],
                        ['text' => 'Always', 'value' => 4],
                    ],
                    'sort_order' => 2,
                    'weight' => 2,
                ],
                [
                    'question_text' => 'How often do you have conflicts in your relationships?',
                    'question_type' => 'multiple_choice',
                    'options' => [
                        ['text' => 'Never', 'value' => 4],
                        ['text' => 'Rarely', 'value' => 3],
                        ['text' => 'Sometimes', 'value' => 2],
                        ['text' => 'Often', 'value' => 1],
                        ['text' => 'Always', 'value' => 0],
                    ],
                    'sort_order' => 3,
                    'weight' => 2,
                ],
                [
                    'question_text' => 'How well do you communicate your needs and feelings?',
                    'question_type' => 'scale',
                    'options' => [
                        ['text' => 'Very Poorly', 'value' => 1],
                        ['text' => 'Poorly', 'value' => 2],
                        ['text' => 'Moderately', 'value' => 3],
                        ['text' => 'Well', 'value' => 4],
                        ['text' => 'Very Well', 'value' => 5],
                    ],
                    'sort_order' => 4,
                    'weight' => 2,
                ],
                [
                    'question_text' => 'How often do you feel supported by your loved ones?',
                    'question_type' => 'multiple_choice',
                    'options' => [
                        ['text' => 'Never', 'value' => 0],
                        ['text' => 'Rarely', 'value' => 1],
                        ['text' => 'Sometimes', 'value' => 2],
                        ['text' => 'Often', 'value' => 3],
                        ['text' => 'Always', 'value' => 4],
                    ],
                    'sort_order' => 5,
                    'weight' => 2,
                ],
                [
                    'question_text' => 'How often do you feel lonely or isolated?',
                    'question_type' => 'multiple_choice',
                    'options' => [
                        ['text' => 'Never', 'value' => 4],
                        ['text' => 'Rarely', 'value' => 3],
                        ['text' => 'Sometimes', 'value' => 2],
                        ['text' => 'Often', 'value' => 1],
                        ['text' => 'Always', 'value' => 0],
                    ],
                    'sort_order' => 6,
                    'weight' => 2,
                ],
                [
                    'question_text' => 'How often do you trust your partner/friends?',
                    'question_type' => 'multiple_choice',
                    'options' => [
                        ['text' => 'Never', 'value' => 0],
                        ['text' => 'Rarely', 'value' => 1],
                        ['text' => 'Sometimes', 'value' => 2],
                        ['text' => 'Often', 'value' => 3],
                        ['text' => 'Always', 'value' => 4],
                    ],
                    'sort_order' => 7,
                    'weight' => 2,
                ],
                [
                    'question_text' => 'How often do you feel appreciated in your relationships?',
                    'question_type' => 'multiple_choice',
                    'options' => [
                        ['text' => 'Never', 'value' => 0],
                        ['text' => 'Rarely', 'value' => 1],
                        ['text' => 'Sometimes', 'value' => 2],
                        ['text' => 'Often', 'value' => 3],
                        ['text' => 'Always', 'value' => 4],
                    ],
                    'sort_order' => 8,
                    'weight' => 2,
                ],
                [
                    'question_text' => 'How often do you spend quality time with loved ones?',
                    'question_type' => 'multiple_choice',
                    'options' => [
                        ['text' => 'Never', 'value' => 0],
                        ['text' => 'Rarely', 'value' => 1],
                        ['text' => 'Sometimes', 'value' => 2],
                        ['text' => 'Often', 'value' => 3],
                        ['text' => 'Always', 'value' => 4],
                    ],
                    'sort_order' => 9,
                    'weight' => 2,
                ],
                [
                    'question_text' => 'How often do you feel emotionally connected to others?',
                    'question_type' => 'multiple_choice',
                    'options' => [
                        ['text' => 'Never', 'value' => 0],
                        ['text' => 'Rarely', 'value' => 1],
                        ['text' => 'Sometimes', 'value' => 2],
                        ['text' => 'Often', 'value' => 3],
                        ['text' => 'Always', 'value' => 4],
                    ],
                    'sort_order' => 10,
                    'weight' => 2,
                ],
            ],
            'General Wellness Assessment' => [
                [
                    'question_text' => 'How would you rate your overall mental health?',
                    'question_type' => 'scale',
                    'options' => [
                        ['text' => 'Poor', 'value' => 1],
                        ['text' => 'Fair', 'value' => 2],
                        ['text' => 'Good', 'value' => 3],
                        ['text' => 'Very Good', 'value' => 4],
                        ['text' => 'Excellent', 'value' => 5],
                    ],
                    'sort_order' => 1,
                    'weight' => 3,
                ],
                [
                    'question_text' => 'How often do you feel happy or content?',
                    'question_type' => 'multiple_choice',
                    'options' => [
                        ['text' => 'Never', 'value' => 0],
                        ['text' => 'Rarely', 'value' => 1],
                        ['text' => 'Sometimes', 'value' => 2],
                        ['text' => 'Often', 'value' => 3],
                        ['text' => 'Always', 'value' => 4],
                    ],
                    'sort_order' => 2,
                    'weight' => 2,
                ],
                [
                    'question_text' => 'How often do you feel confident in yourself?',
                    'question_type' => 'multiple_choice',
                    'options' => [
                        ['text' => 'Never', 'value' => 0],
                        ['text' => 'Rarely', 'value' => 1],
                        ['text' => 'Sometimes', 'value' => 2],
                        ['text' => 'Often', 'value' => 3],
                        ['text' => 'Always', 'value' => 4],
                    ],
                    'sort_order' => 3,
                    'weight' => 2,
                ],
                [
                    'question_text' => 'How often do you engage in activities you enjoy?',
                    'question_type' => 'multiple_choice',
                    'options' => [
                        ['text' => 'Never', 'value' => 0],
                        ['text' => 'Rarely', 'value' => 1],
                        ['text' => 'Sometimes', 'value' => 2],
                        ['text' => 'Often', 'value' => 3],
                        ['text' => 'Always', 'value' => 4],
                    ],
                    'sort_order' => 4,
                    'weight' => 2,
                ],
                [
                    'question_text' => 'How often do you feel motivated to pursue your goals?',
                    'question_type' => 'multiple_choice',
                    'options' => [
                        ['text' => 'Never', 'value' => 0],
                        ['text' => 'Rarely', 'value' => 1],
                        ['text' => 'Sometimes', 'value' => 2],
                        ['text' => 'Often', 'value' => 3],
                        ['text' => 'Always', 'value' => 4],
                    ],
                    'sort_order' => 5,
                    'weight' => 2,
                ],
                [
                    'question_text' => 'How often do you practice self-care activities?',
                    'question_type' => 'multiple_choice',
                    'options' => [
                        ['text' => 'Never', 'value' => 0],
                        ['text' => 'Rarely', 'value' => 1],
                        ['text' => 'Sometimes', 'value' => 2],
                        ['text' => 'Often', 'value' => 3],
                        ['text' => 'Always', 'value' => 4],
                    ],
                    'sort_order' => 6,
                    'weight' => 2,
                ],
                [
                    'question_text' => 'How often do you feel grateful for things in your life?',
                    'question_type' => 'multiple_choice',
                    'options' => [
                        ['text' => 'Never', 'value' => 0],
                        ['text' => 'Rarely', 'value' => 1],
                        ['text' => 'Sometimes', 'value' => 2],
                        ['text' => 'Often', 'value' => 3],
                        ['text' => 'Always', 'value' => 4],
                    ],
                    'sort_order' => 7,
                    'weight' => 2,
                ],
                [
                    'question_text' => 'How often do you feel like you have a sense of purpose?',
                    'question_type' => 'multiple_choice',
                    'options' => [
                        ['text' => 'Never', 'value' => 0],
                        ['text' => 'Rarely', 'value' => 1],
                        ['text' => 'Sometimes', 'value' => 2],
                        ['text' => 'Often', 'value' => 3],
                        ['text' => 'Always', 'value' => 4],
                    ],
                    'sort_order' => 8,
                    'weight' => 2,
                ],
                [
                    'question_text' => 'How often do you feel emotionally balanced?',
                    'question_type' => 'multiple_choice',
                    'options' => [
                        ['text' => 'Never', 'value' => 0],
                        ['text' => 'Rarely', 'value' => 1],
                        ['text' => 'Sometimes', 'value' => 2],
                        ['text' => 'Often', 'value' => 3],
                        ['text' => 'Always', 'value' => 4],
                    ],
                    'sort_order' => 9,
                    'weight' => 2,
                ],
                [
                    'question_text' => 'How often do you feel optimistic about the future?',
                    'question_type' => 'multiple_choice',
                    'options' => [
                        ['text' => 'Never', 'value' => 0],
                        ['text' => 'Rarely', 'value' => 1],
                        ['text' => 'Sometimes', 'value' => 2],
                        ['text' => 'Often', 'value' => 3],
                        ['text' => 'Always', 'value' => 4],
                    ],
                    'sort_order' => 10,
                    'weight' => 2,
                ],
            ],
        ];

        $assessmentQuestions = $questions[$assessment->title] ?? [];

        foreach ($assessmentQuestions as $questionData) {
            $questionData['assessment_id'] = $assessment->id;
            AssessmentQuestion::create($questionData);
        }
    }
}
